language: android

jdk: oraclejdk8

env:
  global:
    - ADB_INSTALL_TIMEOUT=5
  matrix:
    - API=22 ABI=x86_64
    - API=23 ABI=x86_64
    - API=24 ABI=x86_64
    - API=25 ABI=x86_64
    - API=27 ABI=x86_64

android:
  licenses:
    - android-sdk-license-.+
    - '.+'
  components:
    - tools  # use sdkmanager below to get the rest

before_install:
  - echo 'count=0' > /home/travis/.android/repositories.cfg  # avoid harmless sdkmanager warning
  - echo y | sdkmanager "platform-tools" >/dev/null
  - echo y | sdkmanager "build-tools;28.0.3" >/dev/null      # implicit gradle dependency
  - echo y | sdkmanager "platforms;android-$API" >/dev/null  # API of the emulator we will run
  - echo y | sdkmanager "platforms;android-27" >/dev/null    # API of the current compileSdkVersion
  - echo y | sdkmanager --channel=4 "emulator"               # see https://github.com/ankidroid/Anki-Android/pull/5280
  - echo y | sdkmanager "extras;android;m2repository" >/dev/null
  - echo y | sdkmanager "extras;google;m2repository" >/dev/null
  - echo y | sdkmanager "system-images;android-$API;default;$ABI" # install the emulator

before_script:
  - echo no | avdmanager create avd --force -c 1000M -n test -k "system-images;android-$API;default;$ABI"
  - $ANDROID_HOME/emulator/emulator -verbose -avd test -no-accel -no-snapshot -no-window -selinux permissive -qemu -m 2048 &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb logcat -v time > logcat.log &

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - adb shell dumpsys package io.rapidpro.surveyor
  - cat logcat.log
