language: android

env:
  global:
    - ANDROID_TARGET=android-22
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-26
    - ${ANDROID_TARGET}
    - extra
    - extra-android-m2repository
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window -skin 768x1280 &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)

